apiVersion: v2
name: ollama
description: Get up and running with large language models locally.

type: application

version: 1.20.0

appVersion: 0.15.4

annotations:
kubeVersion: "^1.16.0-0"
home: https://ollama.ai/
icon: https://ollama.ai/public/ollama.png
keywords:
  - ai
  - llm
  - llama
  - mistral
sources:
  - https://github.com/ollama/ollama
  - https://github.com/otwld/ollama-helm
dependencies:
  - name: common
    repository: "file://../../../common/charts/common"
    version: 2.31.1
maintainers:
  - name: OTWLD
    email: contact@otwld.com
