{{- /*

SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "docs.docspec.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: docspec
  {{- if or .Values.docspec.deploymentAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.docspec.deploymentAnnotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.docspec.replicaCount }}
  {{- if .Values.docspec.updateStrategy }}
  strategy: {{- toYaml .Values.docspec.updateStrategy | nindent 4 }}
  {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.docspec.podLabels .Values.commonLabels) "context" .) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: docspec
  template:
    metadata:
      {{- if .Values.docspec.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.docspec.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: docspec
    spec:
      {{- include "docs.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ template "docs.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.docspec.automountServiceAccountToken }}
      {{- if .Values.docspec.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.docspec.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.docspec.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.docspec.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.docspec.podAffinityPreset "component" "docs" "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.docspec.podAntiAffinityPreset "component" "docs" "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.docspec.nodeAffinityPreset.type "key" .Values.docspec.nodeAffinityPreset.key "values" .Values.docspec.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.docspec.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.docspec.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.docspec.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.docspec.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.docspec.priorityClassName }}
      priorityClassName: {{ .Values.docspec.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.docspec.schedulerName }}
      schedulerName: {{ .Values.docspec.schedulerName | quote }}
      {{- end }}
      {{- if .Values.docspec.runtimeClassName }}
      runtimeClassName: {{ .Values.docspec.runtimeClassName | quote }}
      {{- end }}
      {{- if .Values.docspec.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.docspec.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.docspec.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.docspec.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.docspec.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.docspec.terminationGracePeriodSeconds }}
      {{- end }}
      initContainers:
        {{- if and .Values.defaultInitContainers.volumePermissions.enabled .Values.persistence.enabled }}
        {{- include "docs.defaultInitContainers.volumePermissions" (dict "context" . "component" "docspec") | nindent 8 }}
        {{- end }}
        {{- if .Values.docspec.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.docspec.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ template "docs.docspec.fullname" . }}
          image: {{ template "docs.docspec.image" . }}
          imagePullPolicy: {{ .Values.docspec.image.pullPolicy }}
          {{- if .Values.docspec.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.docspec.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.docspec.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.docspec.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.docspec.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.docspec.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.docspec.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.docspec.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.docspec.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.docspec.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.docspec.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.docspec.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.docspec.resources }}
          resources: {{- toYaml .Values.docspec.resources | nindent 12 }}
          {{- else if ne .Values.docspec.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.docspec.resourcesPreset) | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.docspec.containerPorts.http }}
            {{- if .Values.docspec.extraContainerPorts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.docspec.extraContainerPorts "context" $) | nindent 12 }}
            {{- end }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.docspec.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.docspec.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.docspec.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.docspec.livenessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /health
              port: {{ .Values.docspec.containerPorts.http }}
          {{- end }}
          {{- if .Values.docspec.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.docspec.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.docspec.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.docspec.readinessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /health
              port: {{ .Values.docspec.containerPorts.http }}
          {{- end }}
          {{- if .Values.docspec.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.docspec.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.docspec.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.docspec.startupProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: {{ .Values.docspec.containerPorts.http }}
          {{- end }}
          {{- end }}
          {{- if .Values.docspec.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.docspec.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
          {{- if .Values.docspec.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.docspec.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.docspec.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.docspec.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: empty-dir
          emptyDir: {}
        {{- if .Values.docspec.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.docspec.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
