{{- /*

SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: clamav
  {{- if or .Values.clamav.deploymentAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.clamav.deploymentAnnotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.clamav.autoscaling.hpa.enabled }}
  replicas: {{ .Values.clamav.replicaCount }}
  {{- end }}
  {{- if .Values.clamav.updateStrategy }}
  strategy: {{- toYaml .Values.clamav.updateStrategy | nindent 4 }}
  {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.clamav.podLabels .Values.commonLabels) "context" .) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: clamav
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: clamav
    spec:
      {{- include "clamav.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ template "clamav.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.clamav.automountServiceAccountToken }}
      {{- if .Values.clamav.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.clamav.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.clamav.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.clamav.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.clamav.podAffinityPreset "component" "clamav" "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.clamav.podAntiAffinityPreset "component" "clamav" "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.clamav.nodeAffinityPreset.type "key" .Values.clamav.nodeAffinityPreset.key "values" .Values.clamav.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.clamav.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.clamav.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.clamav.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.clamav.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.clamav.priorityClassName }}
      priorityClassName: {{ .Values.clamav.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.clamav.schedulerName }}
      schedulerName: {{ .Values.clamav.schedulerName | quote }}
      {{- end }}
      {{- if .Values.clamav.runtimeClassName }}
      runtimeClassName: {{ .Values.clamav.runtimeClassName | quote }}
      {{- end }}
      {{- if .Values.clamav.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.clamav.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.clamav.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.clamav.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.clamav.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.clamav.terminationGracePeriodSeconds }}
      {{- end }}
      initContainers:
        {{/*
        {{- if and .Values.defaultInitContainers.volumePermissions.enabled .Values.persistence.enabled }}
        {{- include "clamav.defaultInitContainers.volumePermissions" (dict "context" . "component" "clamav") | nindent 8 }}
        {{- end }}
        */}}
        {{- if .Values.clamav.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.clamav.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: clamav
          image: {{ template "clamav.image" . }}
          imagePullPolicy: {{ .Values.clamav.image.pullPolicy }}
          {{- if .Values.clamav.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.clamav.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.clamav.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.clamav.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.clamav.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.clamav.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.clamav.configuration.milter.enabled }}
            CLAMAV_NO_MILTERD: "false"
            {{- end }}
            {{- if .Values.clamav.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.clamav.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.clamav.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.clamav.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.clamav.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.clamav.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.clamav.resources }}
          resources: {{- toYaml .Values.clamav.resources | nindent 12 }}
          {{- else if ne .Values.clamav.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.clamav.resourcesPreset) | nindent 12 }}
          {{- end }}
          ports:
            - name: clamav
              containerPort: {{ .Values.clamav.containerPorts.clamav }}
            {{- if .Values.clamav.configuration.milter.enabled }}
            - name: milter
              containerPort: {{ .Values.clamav.containerPorts.milter }}
            {{- end }}
            {{- if .Values.clamav.extraContainerPorts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.clamav.extraContainerPorts "context" $) | nindent 12 }}
            {{- end }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.clamav.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.clamav.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.clamav.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.clamav.livenessProbe "enabled") "context" $) | nindent 12 }}
            exec:
              command:
                - /usr/local/bin/clamdcheck.sh
          {{- end }}
          {{- if .Values.clamav.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.clamav.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.clamav.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.clamav.readinessProbe "enabled") "context" $) | nindent 12 }}
            exec:
              command:
                - /usr/local/bin/clamdcheck.sh
          {{- end }}
          {{- if .Values.clamav.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.clamav.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.clamav.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.clamav.startupProbe "enabled") "context" $) | nindent 12 }}
            exec:
              command:
                - /usr/local/bin/clamdcheck.sh
          {{- end }}
          {{- end }}
          {{- if .Values.clamav.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.clamav.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: database
              mountPath: {{ .Values.persistence.mountPath }}
              {{- if .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath }}
              {{- end }}
            - name: clamd-config
              mountPath: /etc/clamav/clamd.conf
              subPath: clamd.conf
            - name: clamd-config
              mountPath: /etc/clamav/freshclam.conf
              subPath: freshclam.conf
            {{- if .Values.clamav.configuration.milter.enabled }}
            - name: clamd-config
              mountPath: /etc/clamav/
              subPath:
            {{- end }}
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
          {{- if .Values.clamav.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.clamav.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.clamav.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.clamav.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: empty-dir
          emptyDir: {}
        - name: database
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ default (include "common.names.fullname" .) .Values.persistence.existingClaim }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.clamav.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.clamav.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
        - name: clamd-config
          configMap:
            name: {{ include "common.names.fullname" . }}
